import fs from "node:fs";
import os from "node:os";
import path from "node:path";

/**
 * Opt-in, fail-open integration with Claude Code: a Bash->MCP redirect hook and a status line.
 * `efficient-token setup` writes, into the project's `.claude/settings.local.json`
 * (or `~/.claude/settings.json` with `--scope user`):
 *   1. a PreToolUse hook that redirects a read-only Bash drainer to this server's
 *      MCP tools while the server is alive (skip with `--no-hook`), and
 *   2. a `statusLine` that shows the server's health/savings in the session with no
 *      API call (skip with `--no-statusline`).
 * Both are heartbeat-gated and fail-open; the hook never blocks anything when the
 * server is down. `efficient-token uninstall` removes exactly what setup added and
 * never touches a status line the user set themselves.
 */

const SCRIPT_NAME = "efficient-token-redirect.mjs";
const STATUS_SCRIPT_NAME = "efficient-token-status.mjs";
const SERVER_PREFIX = "mcp__efficient-token__";

/** Bare read-only Bash programs and the MCP tool that replaces each. */
const DRAINER_TOOLS: Readonly<Record<string, string>> = {
  grep: "code_search",
  rg: "code_search",
  cat: "code_read",
  head: "code_read",
  tail: "code_read",
  sed: "code_read",
  find: "glob",
  ls: "glob",
};

/**
 * Classify a Bash command for redirection. Returns the MCP tool ONLY for a single,
 * read-only drainer invocation: no shell compounding / redirection / substitution
 * (`| & ; < >` backtick `$(`), the FIRST token is a drainer, and no mutating or
 * blocking flag is present (`sed -i`, `find -delete`/`-exec`, `tail -f`). Anything
 * else returns null (ALLOW): a pipeline or chain — so a protected command like
 * `npm test | grep` is never blocked — a write, a quoted occurrence, an unknown
 * program. When in doubt, ALLOW. {@link redirectScript} mirrors this exactly.
 */
export function matchDrainer(command: string): string | null {
  const cmd = command.trim();
  if (cmd === "") return null;
  if (/[|&;<>`]/.test(cmd) || cmd.includes("$(")) return null;
  const first = (cmd.split(/\s+/)[0] ?? "").toLowerCase();
  const tool = DRAINER_TOOLS[first];
  if (tool === undefined) return null;
  if (first === "sed" && /(^|\s)(-i|--in-place)\b/.test(cmd)) return null;
  if (first === "tail" && /(^|\s)(-f|--follow)\b/.test(cmd)) return null;
  if (first === "find" && /(^|\s)-(delete|exec|execdir|ok|okdir|fprint|fprintf|fls)\b/.test(cmd)) return null;
  return tool;
}

/**
 * The standalone PreToolUse redirect hook (no dependencies). Fail-open by design:
 * ALLOWS on any error, a non-redirectable command, or a stale/missing heartbeat,
 * and only DENIES when the server is alive AND the command is a single read-only
 * drainer with an MCP equivalent. `classify` mirrors {@link matchDrainer}.
 */
export function redirectScript(): string {
  const tools = JSON.stringify(DRAINER_TOOLS);
  return `// efficient-token redirect hook — generated by \`efficient-token setup\`.
// Fail-open: ALLOWS on any error, a non-redirectable command (pipeline, chain,
// redirect, mutation, or no MCP equivalent), or a stale/missing heartbeat. Denies
// (redirecting to an MCP tool) only when the server is alive and the Bash command
// is a single read-only drainer with an MCP equivalent. Remove with
// \`efficient-token uninstall\`.
import { readFileSync, readdirSync, statSync } from "node:fs";

let cmd = "";
try { cmd = (JSON.parse(readFileSync(0, "utf8")).tool_input?.command || "").trim(); }
catch { process.exit(0); }                       // unparseable stdin -> ALLOW

const TOOLS = ${tools};
function classify(c) {
  if (c === "" || /[|&;<>\`]/.test(c) || c.includes("$(")) return null; // compound/redirect -> ALLOW
  const first = (c.split(/\\s+/)[0] || "").toLowerCase();
  const tool = TOOLS[first];
  if (!tool) return null;                          // not a drainer -> ALLOW
  if (first === "sed" && /(^|\\s)(-i|--in-place)\\b/.test(c)) return null;  // in-place write
  if (first === "tail" && /(^|\\s)(-f|--follow)\\b/.test(c)) return null;   // follow (blocks)
  if (first === "find" && /(^|\\s)-(delete|exec|execdir|ok|okdir|fprint|fprintf|fls)\\b/.test(c)) return null; // mutating
  return tool;
}
const tool = classify(cmd);
if (!tool) process.exit(0);                        // not redirectable -> ALLOW

// Liveness: any per-PID heartbeat (or the legacy file) with a fresh mtime. Each
// server writes its own file, so multiple servers on one project don't collide.
const root = process.env.CLAUDE_PROJECT_DIR || ".";
const now = Date.now();
let live = false;
try { for (const f of readdirSync(root + "/.claude/.efficient-token")) { if (!f.endsWith(".json")) continue; try { if (now - statSync(root + "/.claude/.efficient-token/" + f).mtimeMs <= 60000) { live = true; break; } } catch {} } } catch {}
if (!live) { try { if (now - statSync(root + "/.claude/.efficient-token.alive").mtimeMs <= 60000) live = true; } catch {} }
if (!live) process.exit(0);                       // no live server -> ALLOW (fail-open)

process.stdout.write(JSON.stringify({
  hookSpecificOutput: {
    hookEventName: "PreToolUse",
    permissionDecision: "deny",
    permissionDecisionReason:
      \`Token drain — use ${SERVER_PREFIX}\${tool} instead of this Bash command (same data, ~10% the tokens).\`,
  },
}));
process.exit(0);                                  // server alive + drainer -> DENY + redirect
`;
}

/**
 * The standalone status-line script (no dependencies, fast per refresh). Reads the
 * heartbeat the server writes and prints a one-line health summary; no API call.
 * Always prints exactly one line (a status line must never fail or block).
 */
export function statusLineScript(): string {
  return `// efficient-token status line — generated by \`efficient-token setup\`.
// Reads the server heartbeat and prints a one-line health summary; no API call,
// no dependencies. Remove with \`efficient-token uninstall\`.
import { readFileSync, readdirSync, statSync } from "node:fs";

const root = process.env.CLAUDE_PROJECT_DIR || ".";
const dir = root + "/.claude/.efficient-token";
const line = (s) => { process.stdout.write(s + "\\n"); process.exit(0); };
try {
  const now = Date.now();
  const cands = [];
  try { for (const f of readdirSync(dir)) if (f.endsWith(".json")) cands.push(dir + "/" + f); } catch {}
  cands.push(root + "/.claude/.efficient-token.alive"); // legacy single file
  const live = [];
  for (const p of cands) {
    try {
      const age = now - statSync(p).mtimeMs;
      if (age > 60000) continue;
      let d = {};
      try { const r = JSON.parse(readFileSync(p, "utf8")); if (r && typeof r === "object") d = r; } catch {}
      live.push({ d, age });
    } catch {}
  }
  if (live.length === 0) line("efficient-token: not running");
  live.sort((a, b) => a.age - b.age);
  const f = live[0].d;
  const sum = (key) => live.reduce((n, x) => n + (typeof x.d[key] === "number" ? x.d[key] : 0), 0);
  const baselineTokens = sum("baselineTokens"), returnedTokens = sum("returnedTokens"), savedTokens = sum("savedTokens");
  const k = (n) => (n >= 1000 ? (n / 1000).toFixed(1) + "k" : String(n));
  const ver = typeof f.v === "string" ? " v" + f.v : "";
  const tier = typeof f.tier === "string" ? " (" + f.tier + ")" : "";
  let usage = "";
  if (typeof f.baselineTokens === "number" && typeof f.returnedTokens === "number") {
    const sv = savedTokens || (baselineTokens - returnedTokens);
    const pct = baselineTokens > 0 ? " (~" + Math.round((sv / baselineTokens) * 100) + "% less)" : "";
    usage = " · " + k(baselineTokens) + " token read and passed " + k(returnedTokens) + " token to Claude" + pct;
  } else if (savedTokens) {
    usage = " · saved ~" + k(savedTokens) + " tok";
  }
  const multi = live.length > 1 ? " · " + live.length + " servers" : "";
  line("efficient-token" + ver + tier + ": up" + usage + multi);
} catch { line("efficient-token: not running"); }
`;
}

interface HookCmd {
  type?: string;
  command?: string;
  timeout?: number;
}
interface HookEntry {
  matcher?: string;
  hooks?: HookCmd[];
}
interface Settings {
  hooks?: { PreToolUse?: HookEntry[] } & Record<string, unknown>;
  statusLine?: unknown;
  [key: string]: unknown;
}

/** Whether a PreToolUse entry is one efficient-token manages (by script path). */
export function isManagedEntry(entry: HookEntry): boolean {
  return (
    !!entry &&
    Array.isArray(entry.hooks) &&
    entry.hooks.some((h) => typeof h?.command === "string" && h.command.includes(SCRIPT_NAME))
  );
}

/** Whether a statusLine is one efficient-token manages (by status-script path). */
export function isManagedStatusLine(sl: unknown): boolean {
  return (
    !!sl &&
    typeof sl === "object" &&
    typeof (sl as { command?: unknown }).command === "string" &&
    (sl as { command: string }).command.includes(STATUS_SCRIPT_NAME)
  );
}

/** JSON deep-clone — settings are always JSON, so this is exact and safe. */
function clone(settings: Settings): Settings {
  return JSON.parse(JSON.stringify(settings ?? {})) as Settings;
}

/** True only for a plain object (not null, not an array). */
function isPlainObject(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

/**
 * Idempotently add the managed PreToolUse "Bash" hook: drop any prior managed
 * entry (so re-running updates in place) and append a fresh one, leaving every
 * other hook, matcher, and top-level key untouched. A non-object `hooks` (e.g. an
 * array) is coerced to a fresh object so the hook is never silently dropped.
 */
export function deepMergeSetup(settings: Settings, command: string): Settings {
  const s = clone(settings);
  const hooks = (isPlainObject(s.hooks) ? s.hooks : {}) as NonNullable<Settings["hooks"]>;
  const pre = Array.isArray(hooks.PreToolUse) ? hooks.PreToolUse : [];
  const kept = pre.filter((e) => !isManagedEntry(e));
  kept.push({ matcher: "Bash", hooks: [{ type: "command", command, timeout: 10 }] });
  hooks.PreToolUse = kept;
  s.hooks = hooks;
  return s;
}

/** Remove every managed hook entry; prune now-empty PreToolUse / hooks containers. */
export function removeManaged(settings: Settings): Settings {
  const s = clone(settings);
  if (isPlainObject(s.hooks) && Array.isArray(s.hooks.PreToolUse)) {
    s.hooks.PreToolUse = s.hooks.PreToolUse.filter((e) => !isManagedEntry(e));
    if (s.hooks.PreToolUse.length === 0) delete s.hooks.PreToolUse;
    if (Object.keys(s.hooks).length === 0) delete s.hooks;
  }
  return s;
}

/**
 * Set the managed statusLine — but NEVER clobber a status line the user set
 * themselves. If a foreign statusLine exists it is left untouched (and the caller
 * is told how to switch). If none exists, or the existing one is ours, set ours.
 */
export function setManagedStatusLine(settings: Settings, command: string, changed: string[]): Settings {
  const s = clone(settings);
  if (s.statusLine !== undefined && !isManagedStatusLine(s.statusLine)) {
    changed.push(`kept your existing statusLine (unchanged) — to use efficient-token's, set statusLine.command to: ${command}`);
    return s;
  }
  s.statusLine = { type: "command", command };
  changed.push("set the statusLine to show efficient-token health");
  return s;
}

/** Remove the managed statusLine only (a user's own statusLine is left intact). */
export function removeManagedStatusLine(settings: Settings, changed: string[]): Settings {
  const s = clone(settings);
  if (isManagedStatusLine(s.statusLine)) {
    delete s.statusLine;
    changed.push("removed the efficient-token statusLine");
  }
  return s;
}

type Scope = "project" | "user";

interface Target {
  settingsPath: string;
  scriptPath: string;
  statusScriptPath: string;
  command: string;
  statusCommand: string;
  /** The per-server heartbeat dir (`.claude/.efficient-token`); uninstall removes it. */
  beatDir: string;
}

function resolveTarget(scope: Scope, projectRoot: string): Target {
  if (scope === "user") {
    const base = path.join(os.homedir(), ".claude");
    const scriptPath = path.join(base, "hooks", SCRIPT_NAME);
    const statusScriptPath = path.join(base, "hooks", STATUS_SCRIPT_NAME);
    return {
      settingsPath: path.join(base, "settings.json"),
      scriptPath,
      statusScriptPath,
      command: `node "${scriptPath}"`, // absolute: a user-scope hook is shared across projects
      statusCommand: `node "${statusScriptPath}"`,
      beatDir: path.join(projectRoot, ".claude", ".efficient-token"),
    };
  }
  const base = path.join(projectRoot, ".claude");
  return {
    settingsPath: path.join(base, "settings.local.json"),
    scriptPath: path.join(base, "hooks", SCRIPT_NAME),
    statusScriptPath: path.join(base, "hooks", STATUS_SCRIPT_NAME),
    // Hook: Claude Code expands ${CLAUDE_PROJECT_DIR} in hook commands. Status line:
    // a status-line command is run via the shell where that expansion isn't
    // guaranteed (esp. Windows cmd), so use an absolute path — settings.local.json
    // is local/git-ignored anyway, so machine-specific is fine.
    command: `node "\${CLAUDE_PROJECT_DIR}/.claude/hooks/${SCRIPT_NAME}"`,
    statusCommand: `node "${path.join(base, "hooks", STATUS_SCRIPT_NAME)}"`,
    beatDir: path.join(base, ".efficient-token"),
  };
}

/** Load a settings file as JSON; {} if absent/empty. Throws on invalid JSON so a
 *  caller can abort rather than clobber a file it cannot safely parse. */
function loadSettings(file: string): Settings {
  if (!fs.existsSync(file)) return {};
  const raw = fs.readFileSync(file, "utf8");
  if (raw.trim() === "") return {};
  return JSON.parse(raw) as Settings;
}

/** Back up a settings file once, preserving the pristine pre-setup copy across re-runs. */
function backup(file: string, changed: string[]): void {
  if (!fs.existsSync(file)) return;
  const bak = `${file}.bak`;
  if (fs.existsSync(bak)) {
    changed.push(`kept existing backup ${path.basename(bak)}`);
    return;
  }
  fs.copyFileSync(file, bak);
  changed.push(`backed up ${path.basename(file)} -> ${path.basename(bak)}`);
}

function writeScript(file: string, content: string, changed: string[]): void {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
  changed.push(`wrote ${file}`);
}

/** Install the managed hook and/or statusLine. Idempotent; never clobbers. */
export function runSetup(opts: { scope: Scope; projectRoot?: string; hook?: boolean; statusLine?: boolean }): { changed: string[]; target: Target } {
  const projectRoot = opts.projectRoot ?? process.cwd();
  const installHook = opts.hook !== false;
  const installStatus = opts.statusLine !== false;
  const t = resolveTarget(opts.scope, projectRoot);
  const changed: string[] = [];

  // Validate settings BEFORE writing anything, so invalid JSON aborts cleanly.
  let settings: Settings;
  try {
    settings = loadSettings(t.settingsPath);
  } catch {
    throw new Error(`refusing to edit ${t.settingsPath}: it is not valid JSON. Fix or remove it, then re-run.`);
  }

  backup(t.settingsPath, changed);
  if (installHook) {
    writeScript(t.scriptPath, redirectScript(), changed);
    settings = deepMergeSetup(settings, t.command);
    changed.push(`added the managed PreToolUse "Bash" hook`);
  }
  if (installStatus) {
    writeScript(t.statusScriptPath, statusLineScript(), changed);
    settings = setManagedStatusLine(settings, t.statusCommand, changed);
  }

  fs.mkdirSync(path.dirname(t.settingsPath), { recursive: true });
  fs.writeFileSync(t.settingsPath, `${JSON.stringify(settings, null, 2)}\n`);
  changed.push(`updated ${t.settingsPath}`);
  return { changed, target: t };
}

/** Remove exactly what {@link runSetup} added (hook, statusLine, scripts, heartbeat). */
export function runUninstall(opts: { scope: Scope; projectRoot?: string }): { changed: string[]; target: Target } {
  const projectRoot = opts.projectRoot ?? process.cwd();
  const t = resolveTarget(opts.scope, projectRoot);
  const changed: string[] = [];

  if (fs.existsSync(t.settingsPath)) {
    let settings: Settings;
    try {
      settings = loadSettings(t.settingsPath);
    } catch {
      throw new Error(`refusing to edit ${t.settingsPath}: it is not valid JSON.`);
    }
    backup(t.settingsPath, changed);
    settings = removeManaged(settings);
    settings = removeManagedStatusLine(settings, changed);
    fs.writeFileSync(t.settingsPath, `${JSON.stringify(settings, null, 2)}\n`);
    changed.push(`updated ${t.settingsPath}`);
  }
  for (const f of [t.scriptPath, t.statusScriptPath, t.beatDir, `${t.beatDir}.alive`]) {
    try {
      if (fs.existsSync(f)) {
        fs.rmSync(f, { force: true, recursive: true });
        changed.push(`removed ${f}`);
      }
    } catch {
      /* best-effort */
    }
  }
  return { changed, target: t };
}

function parseScope(args: string[]): Scope {
  const i = args.indexOf("--scope");
  if ((i !== -1 && args[i + 1] === "user") || args.includes("--scope=user") || args.includes("--user")) return "user";
  return "project";
}

const HELP = [
  "Usage: efficient-token <setup|uninstall> [--scope project|user] [--no-hook] [--no-statusline]",
  "",
  "  setup            install the opt-in Bash->MCP redirect hook AND a health status line",
  "  uninstall        remove exactly what setup added",
  "  --scope          project (default: .claude/settings.local.json) | user (~/.claude/settings.json)",
  "  --no-hook        set up only the status line (skip the enforcement hook)",
  "  --no-statusline  set up only the enforcement hook (skip the status line)",
  "",
  "Both are heartbeat-gated and fail-open; EFFICIENT_TOKEN_ENFORCE=0 disables the heartbeat.",
].join("\n");

/** Return the args that are not recognized flags (so an unknown flag never runs setup). */
export function unknownArgs(args: string[]): string[] {
  const ok = new Set<number>();
  for (let i = 0; i < args.length; i++) {
    const a = args[i]!;
    if (a === "--scope") {
      ok.add(i);
      if (args[i + 1] === "project" || args[i + 1] === "user") ok.add(i + 1);
    } else if (a === "--scope=project" || a === "--scope=user" || a === "--user" || a === "--no-hook" || a === "--no-statusline") {
      ok.add(i);
    }
  }
  return args.filter((_, i) => !ok.has(i));
}

/** CLI entry for `efficient-token setup|uninstall`. Returns a process exit code. */
export async function runEnforceCli(sub: "setup" | "uninstall", args: string[]): Promise<number> {
  if (args.includes("--help") || args.includes("-h")) {
    process.stdout.write(`${HELP}\n`);
    return 0;
  }
  const unknown = unknownArgs(args);
  if (unknown.length > 0) {
    process.stderr.write(`efficient-token ${sub}: unrecognized argument(s): ${unknown.join(", ")}\n${HELP}\n`);
    return 2;
  }
  const scope = parseScope(args);
  try {
    const res =
      sub === "setup"
        ? runSetup({ scope, hook: !args.includes("--no-hook"), statusLine: !args.includes("--no-statusline") })
        : runUninstall({ scope });
    const lines = [`efficient-token ${sub} (${scope} scope):`, ...res.changed.map((c) => `  - ${c}`)];
    if (sub === "setup") {
      lines.push(
        "",
        "Opt-in, heartbeat-gated, and fail-open: when this server is not running (or",
        "anything errors) your built-in tools work as normal and the status line shows",
        '"not running". Set EFFICIENT_TOKEN_ENFORCE=0 to disable the heartbeat entirely.',
      );
    }
    process.stdout.write(`${lines.join("\n")}\n`);
    return 0;
  } catch (err) {
    process.stderr.write(`efficient-token ${sub} failed: ${err instanceof Error ? err.message : String(err)}\n`);
    return 1;
  }
}
